<?php


use Phinx\Seed\AbstractSeed;

class CountrySeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        // groups data
        $countriesData = [
            [
                'iso' => 'AF',
                'iso3' => 'AFG',
                'numcode' => 4,
                'name' => 'Afghánistán',
            ],
            [
                'iso' => 'AX',
                'iso3' => 'ALA',
                'numcode' => 248,
                'name' => 'Ålandy',
            ],
            [
                'iso' => 'AL',
                'iso3' => 'ALB',
                'numcode' => 8,
                'name' => 'Albánie',
            ],
            [
                'iso' => 'DZ',
                'iso3' => 'DZA',
                'numcode' => 12,
                'name' => 'Alžírsko',
            ],
            [
                'iso' => 'AS',
                'iso3' => 'ASM',
                'numcode' => 16,
                'name' => 'Americká Samoa',
            ],
            [
                'iso' => 'VI',
                'iso3' => 'VIR',
                'numcode' => 850,
                'name' => 'Americké Panenské ostrovy',
            ],
            [
                'iso' => 'AD',
                'iso3' => 'AND',
                'numcode' => 20,
                'name' => 'Andorra',
            ],
            [
                'iso' => 'AO',
                'iso3' => 'AGO',
                'numcode' => 24,
                'name' => 'Angola',
            ],
            [
                'iso' => 'AI',
                'iso3' => 'AIA',
                'numcode' => 660,
                'name' => 'Anguilla',
            ],
            [
                'iso' => 'AQ',
                'iso3' => 'ATA',
                'numcode' => 10,
                'name' => 'Antarktida',
            ],
            [
                'iso' => 'AG',
                'iso3' => 'ATG',
                'numcode' => 28,
                'name' => 'Antigua a Barbuda',
            ],
            [
                'iso' => 'AR',
                'iso3' => 'ARG',
                'numcode' => 32,
                'name' => 'Argentina',
            ],
            [
                'iso' => 'AM',
                'iso3' => 'ARM',
                'numcode' => 51,
                'name' => 'Arménie',
            ],
            [
                'iso' => 'AW',
                'iso3' => 'ABW',
                'numcode' => 533,
                'name' => 'Aruba',
            ],
            [
                'iso' => 'AU',
                'iso3' => 'AUS',
                'numcode' => 36,
                'name' => 'Austrálie',
            ],
            [
                'iso' => 'AZ',
                'iso3' => 'AZE',
                'numcode' => 31,
                'name' => 'Ázerbájdžán',
            ],
            [
                'iso' => 'BS',
                'iso3' => 'BHS',
                'numcode' => 44,
                'name' => 'Bahamy',
            ],
            [
                'iso' => 'BH',
                'iso3' => 'BHR',
                'numcode' => 48,
                'name' => 'Bahrajn',
            ],
            [
                'iso' => 'BD',
                'iso3' => 'BGD',
                'numcode' => 50,
                'name' => 'Bangladéš',
            ],
            [
                'iso' => 'BB',
                'iso3' => 'BRB',
                'numcode' => 52,
                'name' => 'Barbados',
            ],
            [
                'iso' => 'BE',
                'iso3' => 'BEL',
                'numcode' => 56,
                'name' => 'Belgie',
            ],
            [
                'iso' => 'BZ',
                'iso3' => 'BLZ',
                'numcode' => 84,
                'name' => 'Belize',
            ],
            [
                'iso' => 'BY',
                'iso3' => 'BLR',
                'numcode' => 112,
                'name' => 'Bělorusko',
            ],
            [
                'iso' => 'BJ',
                'iso3' => 'BEN',
                'numcode' => 204,
                'name' => 'Benin',
            ],
            [
                'iso' => 'BM',
                'iso3' => 'BMU',
                'numcode' => 60,
                'name' => 'Bermudy',
            ],
            [
                'iso' => 'BT',
                'iso3' => 'BTN',
                'numcode' => 64,
                'name' => 'Bhútán',
            ],
            [
                'iso' => 'BO',
                'iso3' => 'BOL',
                'numcode' => 68,
                'name' => 'Bolívie',
            ],
            [
                'iso' => 'BA',
                'iso3' => 'BIH',
                'numcode' => 70,
                'name' => 'Bosna a Hercegovina',
            ],
            [
                'iso' => 'BW',
                'iso3' => 'BWA',
                'numcode' => 72,
                'name' => 'Botswana',
            ],
            [
                'iso' => 'BV',
                'iso3' => 'BVT',
                'numcode' => 74,
                'name' => 'Bouvetův ostrov',
            ],
            [
                'iso' => 'BR',
                'iso3' => 'BRA',
                'numcode' => 76,
                'name' => 'Brazílie',
            ],
            [
                'iso' => 'IO',
                'iso3' => 'IOT',
                'numcode' => 86,
                'name' => 'Britské indickooceánské území',
            ],
            [
                'iso' => 'VG',
                'iso3' => 'VGB',
                'numcode' => 92,
                'name' => 'Britské Panenské ostrovy',
            ],
            [
                'iso' => 'BN',
                'iso3' => 'BRN',
                'numcode' => 96,
                'name' => 'Brunej',
            ],
            [
                'iso' => 'BG',
                'iso3' => 'BGR',
                'numcode' => 100,
                'name' => 'Bulharsko',
            ],
            [
                'iso' => 'BF',
                'iso3' => 'BFA',
                'numcode' => 854,
                'name' => 'Burkina Faso',
            ],
            [
                'iso' => 'BI',
                'iso3' => 'BDI',
                'numcode' => 108,
                'name' => 'Burundi',
            ],
            [
                'iso' => 'CK',
                'iso3' => 'COK',
                'numcode' => 184,
                'name' => 'Cookovy ostrovy',
            ],
            [
                'iso' => 'TD',
                'iso3' => 'TCD',
                'numcode' => 148,
                'name' => 'Čad',
            ],
            [
                'iso' => 'ME',
                'iso3' => 'MNE',
                'numcode' => 499,
                'name' => 'Černá Hora',
            ],
            [
                'iso' => 'CZ',
                'iso3' => 'CZE',
                'numcode' => 203,
                'name' => 'Česká republika',
            ],
            [
                'iso' => 'CN',
                'iso3' => 'CHN',
                'numcode' => 156,
                'name' => 'Čína',
            ],
            [
                'iso' => 'DK',
                'iso3' => 'DNK',
                'numcode' => 208,
                'name' => 'Dánsko',
            ],
            [
                'iso' => 'CD',
                'iso3' => 'COD',
                'numcode' => 180,
                'name' => 'Demokratická republika Kongo',
            ],
            [
                'iso' => 'DM',
                'iso3' => 'DMA',
                'numcode' => 212,
                'name' => 'Dominika',
            ],
            [
                'iso' => 'DO',
                'iso3' => 'DOM',
                'numcode' => 214,
                'name' => 'Dominikánská republika',
            ],
            [
                'iso' => 'DJ',
                'iso3' => 'DJI',
                'numcode' => 262,
                'name' => 'Džibutsko',
            ],
            [
                'iso' => 'EG',
                'iso3' => 'EGY',
                'numcode' => 818,
                'name' => 'Egypt',
            ],
            [
                'iso' => 'EC',
                'iso3' => 'ECU',
                'numcode' => 218,
                'name' => 'Ekvádor',
            ],
            [
                'iso' => 'ER',
                'iso3' => 'ERI',
                'numcode' => 232,
                'name' => 'Eritrea',
            ],
            [
                'iso' => 'EE',
                'iso3' => 'EST',
                'numcode' => 233,
                'name' => 'Estonsko',
            ],
            [
                'iso' => 'ET',
                'iso3' => 'ETH',
                'numcode' => 231,
                'name' => 'Etiopie',
            ],
            [
                'iso' => 'FO',
                'iso3' => 'FRO',
                'numcode' => 234,
                'name' => 'Faerské ostrovy',
            ],
            [
                'iso' => 'FK',
                'iso3' => 'FLK',
                'numcode' => 238,
                'name' => 'Falklandy (Malvíny)',
            ],
            [
                'iso' => 'FJ',
                'iso3' => 'FJI',
                'numcode' => 242,
                'name' => 'Fidži',
            ],
            [
                'iso' => 'PH',
                'iso3' => 'PHL',
                'numcode' => 608,
                'name' => 'Filipíny',
            ],
            [
                'iso' => 'FI',
                'iso3' => 'FIN',
                'numcode' => 246,
                'name' => 'Finsko',
            ],
            [
                'iso' => 'FR',
                'iso3' => 'FRA',
                'numcode' => 250,
                'name' => 'Francie',
            ],
            [
                'iso' => 'GF',
                'iso3' => 'GUF',
                'numcode' => 254,
                'name' => 'Francouzská Guyana',
            ],
            [
                'iso' => 'TF',
                'iso3' => 'ATF',
                'numcode' => 260,
                'name' => 'Francouzská jižní a antarktická území',
            ],
            [
                'iso' => 'PF',
                'iso3' => 'PYF',
                'numcode' => 258,
                'name' => 'Francouzská Polynésie',
            ],
            [
                'iso' => 'GA',
                'iso3' => 'GAB',
                'numcode' => 266,
                'name' => 'Gabon',
            ],
            [
                'iso' => 'GM',
                'iso3' => 'GMB',
                'numcode' => 270,
                'name' => 'Gambie',
            ],
            [
                'iso' => 'GH',
                'iso3' => 'GHA',
                'numcode' => 288,
                'name' => 'Ghana',
            ],
            [
                'iso' => 'GI',
                'iso3' => 'GIB',
                'numcode' => 292,
                'name' => 'Gibraltar',
            ],
            [
                'iso' => 'GD',
                'iso3' => 'GRD',
                'numcode' => 308,
                'name' => 'Grenada',
            ],
            [
                'iso' => 'GL',
                'iso3' => 'GRL',
                'numcode' => 304,
                'name' => 'Grónsko',
            ],
            [
                'iso' => 'GE',
                'iso3' => 'GEO',
                'numcode' => 268,
                'name' => 'Gruzie',
            ],
            [
                'iso' => 'GP',
                'iso3' => 'GLP',
                'numcode' => 312,
                'name' => 'Guadeloupe',
            ],
            [
                'iso' => 'GU',
                'iso3' => 'GUM',
                'numcode' => 316,
                'name' => 'Guam',
            ],
            [
                'iso' => 'GT',
                'iso3' => 'GTM',
                'numcode' => 320,
                'name' => 'Guatemala',
            ],
            [
                'iso' => 'GN',
                'iso3' => 'GIN',
                'numcode' => 324,
                'name' => 'Guinea',
            ],
            [
                'iso' => 'GW',
                'iso3' => 'GNB',
                'numcode' => 624,
                'name' => 'Guinea-Bissau',
            ],
            [
                'iso' => 'GG',
                'iso3' => 'GGY',
                'numcode' => 831,
                'name' => 'Guernsey',
            ],
            [
                'iso' => 'GY',
                'iso3' => 'GUY',
                'numcode' => 328,
                'name' => 'Guyana',
            ],
            [
                'iso' => 'HT',
                'iso3' => 'HTI',
                'numcode' => 332,
                'name' => 'Haiti',
            ],
            [
                'iso' => 'HM',
                'iso3' => 'HMD',
                'numcode' => 334,
                'name' => 'Heardův ostrov a McDonaldovy ostrovy',
            ],
            [
                'iso' => 'HN',
                'iso3' => 'HND',
                'numcode' => 340,
                'name' => 'Honduras',
            ],
            [
                'iso' => 'HK',
                'iso3' => 'HKG',
                'numcode' => 344,
                'name' => 'Hongkong',
            ],
            [
                'iso' => 'CL',
                'iso3' => 'CHL',
                'numcode' => 152,
                'name' => 'Chile',
            ],
            [
                'iso' => 'HR',
                'iso3' => 'HRV',
                'numcode' => 191,
                'name' => 'Chorvatsko',
            ],
            [
                'iso' => 'IN',
                'iso3' => 'IND',
                'numcode' => 356,
                'name' => 'Indie',
            ],
            [
                'iso' => 'ID',
                'iso3' => 'IDN',
                'numcode' => 360,
                'name' => 'Indonésie',
            ],
            [
                'iso' => 'IQ',
                'iso3' => 'IRQ',
                'numcode' => 368,
                'name' => 'Irák',
            ],
            [
                'iso' => 'IR',
                'iso3' => 'IRN',
                'numcode' => 364,
                'name' => 'Írán',
            ],
            [
                'iso' => 'IE',
                'iso3' => 'IRL',
                'numcode' => 372,
                'name' => 'Irsko',
            ],
            [
                'iso' => 'IS',
                'iso3' => 'ISL',
                'numcode' => 352,
                'name' => 'Island',
            ],
            [
                'iso' => 'IT',
                'iso3' => 'ITA',
                'numcode' => 380,
                'name' => 'Itálie',
            ],
            [
                'iso' => 'IL',
                'iso3' => 'ISR',
                'numcode' => 376,
                'name' => 'Izrael',
            ],
            [
                'iso' => 'JM',
                'iso3' => 'JAM',
                'numcode' => 388,
                'name' => 'Jamajka',
            ],
            [
                'iso' => 'JP',
                'iso3' => 'JPN',
                'numcode' => 392,
                'name' => 'Japonsko',
            ],
            [
                'iso' => 'YE',
                'iso3' => 'YEM',
                'numcode' => 887,
                'name' => 'Jemen',
            ],
            [
                'iso' => 'JE',
                'iso3' => 'JEY',
                'numcode' => 832,
                'name' => 'Jersey',
            ],
            [
                'iso' => 'ZA',
                'iso3' => 'ZAF',
                'numcode' => 710,
                'name' => 'Jihoafrická republika',
            ],
            [
                'iso' => 'GS',
                'iso3' => 'SGS',
                'numcode' => 239,
                'name' => 'Jižní Georgie a Jižní Sandwichovy ostrovy',
            ],
            [
                'iso' => 'KR',
                'iso3' => 'KOR',
                'numcode' => 410,
                'name' => 'Jižní Korea',
            ],
            [
                'iso' => 'JO',
                'iso3' => 'JOR',
                'numcode' => 400,
                'name' => 'Jordánsko',
            ],
            [
                'iso' => 'KY',
                'iso3' => 'CYM',
                'numcode' => 136,
                'name' => 'Kajmanské ostrovy',
            ],
            [
                'iso' => 'KH',
                'iso3' => 'KHM',
                'numcode' => 116,
                'name' => 'Kambodža',
            ],
            [
                'iso' => 'CM',
                'iso3' => 'CMR',
                'numcode' => 120,
                'name' => 'Kamerun',
            ],
            [
                'iso' => 'CA',
                'iso3' => 'CAN',
                'numcode' => 124,
                'name' => 'Kanada',
            ],
            [
                'iso' => 'CV',
                'iso3' => 'CPV',
                'numcode' => 132,
                'name' => 'Kapverdy',
            ],
            [
                'iso' => 'QA',
                'iso3' => 'QAT',
                'numcode' => 634,
                'name' => 'Katar',
            ],
            [
                'iso' => 'KZ',
                'iso3' => 'KAZ',
                'numcode' => 398,
                'name' => 'Kazachstán',
            ],
            [
                'iso' => 'KE',
                'iso3' => 'KEN',
                'numcode' => 404,
                'name' => 'Keňa',
            ],
            [
                'iso' => 'KI',
                'iso3' => 'KIR',
                'numcode' => 296,
                'name' => 'Kiribati',
            ],
            [
                'iso' => 'CC',
                'iso3' => 'CCK',
                'numcode' => 166,
                'name' => 'Kokosové ostrovy',
            ],
            [
                'iso' => 'CO',
                'iso3' => 'COL',
                'numcode' => 170,
                'name' => 'Kolumbie',
            ],
            [
                'iso' => 'KM',
                'iso3' => 'COM',
                'numcode' => 174,
                'name' => 'Komory',
            ],
            [
                'iso' => 'CG',
                'iso3' => 'COG',
                'numcode' => 178,
                'name' => 'Kongo',
            ],
            [
                'iso' => 'CR',
                'iso3' => 'CRI',
                'numcode' => 188,
                'name' => 'Kostarika',
            ],
            [
                'iso' => 'CU',
                'iso3' => 'CUB',
                'numcode' => 192,
                'name' => 'Kuba',
            ],
            [
                'iso' => 'KW',
                'iso3' => 'KWT',
                'numcode' => 414,
                'name' => 'Kuvajt',
            ],
            [
                'iso' => 'CY',
                'iso3' => 'CYP',
                'numcode' => 196,
                'name' => 'Kypr',
            ],
            [
                'iso' => 'KG',
                'iso3' => 'KGZ',
                'numcode' => 417,
                'name' => 'Kyrgyzstán',
            ],
            [
                'iso' => 'LA',
                'iso3' => 'LAO',
                'numcode' => 418,
                'name' => 'Laos',
            ],
            [
                'iso' => 'LS',
                'iso3' => 'LSO',
                'numcode' => 426,
                'name' => 'Lesotho',
            ],
            [
                'iso' => 'LB',
                'iso3' => 'LBN',
                'numcode' => 422,
                'name' => 'Libanon',
            ],
            [
                'iso' => 'LR',
                'iso3' => 'LBR',
                'numcode' => 430,
                'name' => 'Libérie',
            ],
            [
                'iso' => 'LY',
                'iso3' => 'LBY',
                'numcode' => 434,
                'name' => 'Libye',
            ],
            [
                'iso' => 'LI',
                'iso3' => 'LIE',
                'numcode' => 438,
                'name' => 'Lichtenštejnsko',
            ],
            [
                'iso' => 'LT',
                'iso3' => 'LTU',
                'numcode' => 440,
                'name' => 'Litva',
            ],
            [
                'iso' => 'LV',
                'iso3' => 'LVA',
                'numcode' => 428,
                'name' => 'Lotyšsko',
            ],
            [
                'iso' => 'LU',
                'iso3' => 'LUX',
                'numcode' => 442,
                'name' => 'Lucembursko',
            ],
            [
                'iso' => 'MO',
                'iso3' => 'MAC',
                'numcode' => 446,
                'name' => 'Macao',
            ],
            [
                'iso' => 'MG',
                'iso3' => 'MDG',
                'numcode' => 450,
                'name' => 'Madagaskar',
            ],
            [
                'iso' => 'HU',
                'iso3' => 'HUN',
                'numcode' => 348,
                'name' => 'Maďarsko',
            ],
            [
                'iso' => 'MK',
                'iso3' => 'MKD',
                'numcode' => 807,
                'name' => 'Makedonie',
            ],
            [
                'iso' => 'MY',
                'iso3' => 'MYS',
                'numcode' => 458,
                'name' => 'Malajsie',
            ],
            [
                'iso' => 'MW',
                'iso3' => 'MWI',
                'numcode' => 454,
                'name' => 'Malawi',
            ],
            [
                'iso' => 'MV',
                'iso3' => 'MDV',
                'numcode' => 462,
                'name' => 'Maledivy',
            ],
            [
                'iso' => 'ML',
                'iso3' => 'MLI',
                'numcode' => 466,
                'name' => 'Mali',
            ],
            [
                'iso' => 'MT',
                'iso3' => 'MLT',
                'numcode' => 470,
                'name' => 'Malta',
            ],
            [
                'iso' => 'IM',
                'iso3' => 'IMN',
                'numcode' => 833,
                'name' => 'Ostrov Man',
            ],
            [
                'iso' => 'MA',
                'iso3' => 'MAR',
                'numcode' => 504,
                'name' => 'Maroko',
            ],
            [
                'iso' => 'MH',
                'iso3' => 'MHL',
                'numcode' => 584,
                'name' => 'Marshallovy ostrovy',
            ],
            [
                'iso' => 'MQ',
                'iso3' => 'MTQ',
                'numcode' => 474,
                'name' => 'Martinik',
            ],
            [
                'iso' => 'MU',
                'iso3' => 'MUS',
                'numcode' => 480,
                'name' => 'Mauricius',
            ],
            [
                'iso' => 'MR',
                'iso3' => 'MRT',
                'numcode' => 478,
                'name' => 'Mauritánie',
            ],
            [
                'iso' => 'YT',
                'iso3' => 'MYT',
                'numcode' => 175,
                'name' => 'Mayotte',
            ],
            [
                'iso' => 'UM',
                'iso3' => 'UMI',
                'numcode' => 581,
                'name' => 'Menší odlehlé ostrovy USA',
            ],
            [
                'iso' => 'MX',
                'iso3' => 'MEX',
                'numcode' => 484,
                'name' => 'Mexiko',
            ],
            [
                'iso' => 'FM',
                'iso3' => 'FSM',
                'numcode' => 583,
                'name' => 'Mikronésie',
            ],
            [
                'iso' => 'MD',
                'iso3' => 'MDA',
                'numcode' => 498,
                'name' => 'Moldavsko',
            ],
            [
                'iso' => 'MC',
                'iso3' => 'MCO',
                'numcode' => 492,
                'name' => 'Monako',
            ],
            [
                'iso' => 'MN',
                'iso3' => 'MNG',
                'numcode' => 496,
                'name' => 'Mongolsko',
            ],
            [
                'iso' => 'MS',
                'iso3' => 'MSR',
                'numcode' => 500,
                'name' => 'Montserrat',
            ],
            [
                'iso' => 'MZ',
                'iso3' => 'MOZ',
                'numcode' => 508,
                'name' => 'Mosambik',
            ],
            [
                'iso' => 'MM',
                'iso3' => 'MMR',
                'numcode' => 104,
                'name' => 'Myanmar',
            ],
            [
                'iso' => 'NA',
                'iso3' => 'NAM',
                'numcode' => 516,
                'name' => 'Namibie',
            ],
            [
                'iso' => 'NR',
                'iso3' => 'NRU',
                'numcode' => 520,
                'name' => 'Nauru',
            ],
            [
                'iso' => 'DE',
                'iso3' => 'DEU',
                'numcode' => 276,
                'name' => 'Německo',
            ],
            [
                'iso' => 'NP',
                'iso3' => 'NPL',
                'numcode' => 524,
                'name' => 'Nepál',
            ],
            [
                'iso' => 'NE',
                'iso3' => 'NER',
                'numcode' => 562,
                'name' => 'Niger',
            ],
            [
                'iso' => 'NG',
                'iso3' => 'NGA',
                'numcode' => 566,
                'name' => 'Nigérie',
            ],
            [
                'iso' => 'NI',
                'iso3' => 'NIC',
                'numcode' => 558,
                'name' => 'Nikaragua',
            ],
            [
                'iso' => 'NU',
                'iso3' => 'NIU',
                'numcode' => 570,
                'name' => 'Niue',
            ],
            [
                'iso' => 'AN',
                'iso3' => 'ANT',
                'numcode' => 530,
                'name' => 'Nizozemské Antily',
            ],
            [
                'iso' => 'NL',
                'iso3' => 'NLD',
                'numcode' => 528,
                'name' => 'Nizozemsko',
            ],
            [
                'iso' => 'NF',
                'iso3' => 'NFK',
                'numcode' => 574,
                'name' => 'Norfolk',
            ],
            [
                'iso' => 'NO',
                'iso3' => 'NOR',
                'numcode' => 578,
                'name' => 'Norsko',
            ],
            [
                'iso' => 'NC',
                'iso3' => 'NCL',
                'numcode' => 540,
                'name' => 'Nová Kaledonie',
            ],
            [
                'iso' => 'NZ',
                'iso3' => 'NZL',
                'numcode' => 554,
                'name' => 'Nový Zéland',
            ],
            [
                'iso' => 'OM',
                'iso3' => 'OMN',
                'numcode' => 512,
                'name' => 'Omán',
            ],
            [
                'iso' => 'PK',
                'iso3' => 'PAK',
                'numcode' => 586,
                'name' => 'Pákistán',
            ],
            [
                'iso' => 'PW',
                'iso3' => 'PLW',
                'numcode' => 585,
                'name' => 'Palau',
            ],
            [
                'iso' => 'PS',
                'iso3' => 'PSE',
                'numcode' => 275,
                'name' => 'Palestinská autonomie',
            ],
            [
                'iso' => 'PA',
                'iso3' => 'PAN',
                'numcode' => 591,
                'name' => 'Panama',
            ],
            [
                'iso' => 'PG',
                'iso3' => 'PNG',
                'numcode' => 598,
                'name' => 'Papua-Nová Guinea',
            ],
            [
                'iso' => 'PY',
                'iso3' => 'PRY',
                'numcode' => 600,
                'name' => 'Paraguay',
            ],
            [
                'iso' => 'PE',
                'iso3' => 'PER',
                'numcode' => 604,
                'name' => 'Peru',
            ],
            [
                'iso' => 'PN',
                'iso3' => 'PCN',
                'numcode' => 612,
                'name' => 'Pitcairnovy ostrovy',
            ],
            [
                'iso' => 'CI',
                'iso3' => 'CIV',
                'numcode' => 384,
                'name' => 'Pobřeží slonoviny',
            ],
            [
                'iso' => 'PL',
                'iso3' => 'POL',
                'numcode' => 616,
                'name' => 'Polsko',
            ],
            [
                'iso' => 'PR',
                'iso3' => 'PRI',
                'numcode' => 630,
                'name' => 'Portoriko',
            ],
            [
                'iso' => 'PT',
                'iso3' => 'PRT',
                'numcode' => 620,
                'name' => 'Portugalsko',
            ],
            [
                'iso' => 'AT',
                'iso3' => 'AUT',
                'numcode' => 40,
                'name' => 'Rakousko',
            ],
            [
                'iso' => 'RE',
                'iso3' => 'REU',
                'numcode' => 638,
                'name' => 'Réunion',
            ],
            [
                'iso' => 'GQ',
                'iso3' => 'GNQ',
                'numcode' => 226,
                'name' => 'Rovníková Guinea',
            ],
            [
                'iso' => 'RO',
                'iso3' => 'ROU',
                'numcode' => 642,
                'name' => 'Rumunsko',
            ],
            [
                'iso' => 'RU',
                'iso3' => 'RUS',
                'numcode' => 643,
                'name' => 'Rusko',
            ],
            [
                'iso' => 'RW',
                'iso3' => 'RWA',
                'numcode' => 646,
                'name' => 'Rwanda',
            ],
            [
                'iso' => 'GR',
                'iso3' => 'GRC',
                'numcode' => 300,
                'name' => 'Řecko',
            ],
            [
                'iso' => 'BL',
                'iso3' => 'BLM',
                'numcode' => 652,
                'name' => 'Saint-Barthélemy',
            ],
            [
                'iso' => 'MF',
                'iso3' => 'MAF',
                'numcode' => 663,
                'name' => 'Saint-Martin',
            ],
            [
                'iso' => 'PM',
                'iso3' => 'SPM',
                'numcode' => 666,
                'name' => 'Saint-Pierre a Miquelon',
            ],
            [
                'iso' => 'SV',
                'iso3' => 'SLV',
                'numcode' => 222,
                'name' => 'Salvador',
            ],
            [
                'iso' => 'WS',
                'iso3' => 'WSM',
                'numcode' => 882,
                'name' => 'Samoa',
            ],
            [
                'iso' => 'SM',
                'iso3' => 'SMR',
                'numcode' => 674,
                'name' => 'San Marino',
            ],
            [
                'iso' => 'SA',
                'iso3' => 'SAU',
                'numcode' => 682,
                'name' => 'Saúdská Arábie',
            ],
            [
                'iso' => 'SN',
                'iso3' => 'SEN',
                'numcode' => 686,
                'name' => 'Senegal',
            ],
            [
                'iso' => 'KP',
                'iso3' => 'PRK',
                'numcode' => 408,
                'name' => 'Severní Korea',
            ],
            [
                'iso' => 'MP',
                'iso3' => 'MNP',
                'numcode' => 580,
                'name' => 'Severní Mariany',
            ],
            [
                'iso' => 'SC',
                'iso3' => 'SYC',
                'numcode' => 690,
                'name' => 'Seychely',
            ],
            [
                'iso' => 'SL',
                'iso3' => 'SLE',
                'numcode' => 694,
                'name' => 'Sierra Leone',
            ],
            [
                'iso' => 'SG',
                'iso3' => 'SGP',
                'numcode' => 702,
                'name' => 'Singapur',
            ],
            [
                'iso' => 'SK',
                'iso3' => 'SVK',
                'numcode' => 703,
                'name' => 'Slovensko',
            ],
            [
                'iso' => 'SI',
                'iso3' => 'SVN',
                'numcode' => 705,
                'name' => 'Slovinsko',
            ],
            [
                'iso' => 'SO',
                'iso3' => 'SOM',
                'numcode' => 706,
                'name' => 'Somálsko',
            ],
            [
                'iso' => 'AE',
                'iso3' => 'ARE',
                'numcode' => 784,
                'name' => 'Spojené arabské emiráty',
            ],
            [
                'iso' => 'GB',
                'iso3' => 'GBR',
                'numcode' => 826,
                'name' => 'Spojené království',
            ],
            [
                'iso' => 'US',
                'iso3' => 'USA',
                'numcode' => 840,
                'name' => 'Spojené státy americké',
            ],
            [
                'iso' => 'RS',
                'iso3' => 'SRB',
                'numcode' => 688,
                'name' => 'Srbsko',
            ],
            [
                'iso' => 'CF',
                'iso3' => 'CAF',
                'numcode' => 140,
                'name' => 'Středoafrická republika',
            ],
            [
                'iso' => 'SD',
                'iso3' => 'SDN',
                'numcode' => 736,
                'name' => 'Súdán',
            ],
            [
                'iso' => 'SR',
                'iso3' => 'SUR',
                'numcode' => 740,
                'name' => 'Surinam',
            ],
            [
                'iso' => 'SH',
                'iso3' => 'SHN',
                'numcode' => 654,
                'name' => 'Svatá Helena',
            ],
            [
                'iso' => 'LC',
                'iso3' => 'LCA',
                'numcode' => 662,
                'name' => 'Svatá Lucie',
            ],
            [
                'iso' => 'KN',
                'iso3' => 'KNA',
                'numcode' => 659,
                'name' => 'Svatý Kryštof a Nevis',
            ],
            [
                'iso' => 'ST',
                'iso3' => 'STP',
                'numcode' => 678,
                'name' => 'Svatý Tomáš a Princův ostrov',
            ],
            [
                'iso' => 'VC',
                'iso3' => 'VCT',
                'numcode' => 670,
                'name' => 'Svatý Vincenc a Grenadiny',
            ],
            [
                'iso' => 'SZ',
                'iso3' => 'SWZ',
                'numcode' => 748,
                'name' => 'Svazijsko',
            ],
            [
                'iso' => 'SY',
                'iso3' => 'SYR',
                'numcode' => 760,
                'name' => 'Sýrie',
            ],
            [
                'iso' => 'SB',
                'iso3' => 'SLB',
                'numcode' => 90,
                'name' => 'Šalamounovy ostrovy',
            ],
            [
                'iso' => 'ES',
                'iso3' => 'ESP',
                'numcode' => 724,
                'name' => 'Španělsko',
            ],
            [
                'iso' => 'SJ',
                'iso3' => 'SJM',
                'numcode' => 744,
                'name' => 'Špicberky a Jan Mayen',
            ],
            [
                'iso' => 'LK',
                'iso3' => 'LKA',
                'numcode' => 144,
                'name' => 'Šrí Lanka',
            ],
            [
                'iso' => 'SE',
                'iso3' => 'SWE',
                'numcode' => 752,
                'name' => 'Švédsko',
            ],
            [
                'iso' => 'CH',
                'iso3' => 'CHE',
                'numcode' => 756,
                'name' => 'Švýcarsko',
            ],
            [
                'iso' => 'TJ',
                'iso3' => 'TJK',
                'numcode' => 762,
                'name' => 'Tádžikistán',
            ],
            [
                'iso' => 'TZ',
                'iso3' => 'TZA',
                'numcode' => 834,
                'name' => 'Tanzanie',
            ],
            [
                'iso' => 'TH',
                'iso3' => 'THA',
                'numcode' => 764,
                'name' => 'Thajsko',
            ],
            [
                'iso' => 'TW',
                'iso3' => 'TWN',
                'numcode' => 158,
                'name' => 'Tchaj-wan',
            ],
            [
                'iso' => 'TG',
                'iso3' => 'TGO',
                'numcode' => 768,
                'name' => 'Togo',
            ],
            [
                'iso' => 'TK',
                'iso3' => 'TKL',
                'numcode' => 772,
                'name' => 'Tokelau',
            ],
            [
                'iso' => 'TO',
                'iso3' => 'TON',
                'numcode' => 776,
                'name' => 'Tonga',
            ],
            [
                'iso' => 'TT',
                'iso3' => 'TTO',
                'numcode' => 780,
                'name' => 'Trinidad a Tobago',
            ],
            [
                'iso' => 'TN',
                'iso3' => 'TUN',
                'numcode' => 788,
                'name' => 'Tunisko',
            ],
            [
                'iso' => 'TR',
                'iso3' => 'TUR',
                'numcode' => 792,
                'name' => 'Turecko',
            ],
            [
                'iso' => 'TM',
                'iso3' => 'TKM',
                'numcode' => 795,
                'name' => 'Turkmenistán',
            ],
            [
                'iso' => 'TC',
                'iso3' => 'TCA',
                'numcode' => 796,
                'name' => 'Turks a Caicos',
            ],
            [
                'iso' => 'TV',
                'iso3' => 'TUV',
                'numcode' => 798,
                'name' => 'Tuvalu',
            ],
            [
                'iso' => 'UG',
                'iso3' => 'UGA',
                'numcode' => 800,
                'name' => 'Uganda',
            ],
            [
                'iso' => 'UA',
                'iso3' => 'UKR',
                'numcode' => 804,
                'name' => 'Ukrajina',
            ],
            [
                'iso' => 'UY',
                'iso3' => 'URY',
                'numcode' => 858,
                'name' => 'Uruguay',
            ],
            [
                'iso' => 'UZ',
                'iso3' => 'UZB',
                'numcode' => 860,
                'name' => 'Uzbekistán',
            ],
            [
                'iso' => 'CX',
                'iso3' => 'CXR',
                'numcode' => 162,
                'name' => 'Vánoční ostrov',
            ],
            [
                'iso' => 'VU',
                'iso3' => 'VUT',
                'numcode' => 548,
                'name' => 'Vanuatu',
            ],
            [
                'iso' => 'VA',
                'iso3' => 'VAT',
                'numcode' => 336,
                'name' => 'Vatikán',
            ],
            [
                'iso' => 'VE',
                'iso3' => 'VEN',
                'numcode' => 862,
                'name' => 'Venezuela',
            ],
            [
                'iso' => 'VN',
                'iso3' => 'VNM',
                'numcode' => 704,
                'name' => 'Vietnam',
            ],
            [
                'iso' => 'TL',
                'iso3' => 'TLS',
                'numcode' => 626,
                'name' => 'Východní Timor',
            ],
            [
                'iso' => 'WF',
                'iso3' => 'WLF',
                'numcode' => 876,
                'name' => 'Wallis a Futuna',
            ],
            [
                'iso' => 'ZM',
                'iso3' => 'ZMB',
                'numcode' => 894,
                'name' => 'Zambie',
            ],
            [
                'iso' => 'EH',
                'iso3' => 'ESH',
                'numcode' => 732,
                'name' => 'Západní Sahara',
            ],
            [
                'iso' => 'ZW',
                'iso3' => 'ZWE',
                'numcode' => 716,
                'name' => 'Zimbabwe',
            ],                      
        ];

        $countries = $this->table('countries');
        $countries->insert($countriesData)->save();
    }
}
