app:
    port: 3001
    secret: "trnsctns"
    logFormat: "[:date[clf]] :method :url :status :response-time ms"
db:
    url: "mongodb://gymitdev:gymit2019@ds129733.mlab.com:29733/gymit-client-dev"
    config: {"useNewUrlParser": true, "useFindAndModify": false, "useCreateIndex": true}