app:
    port: 3003
    secret: "lkor"
    logFormat: "[:date[clf]] :method :url :status :response-time ms"
db:
    url: "mongodb://dev:gymit2019@ds151817.mlab.com:51817/gymit"
    config: {"useNewUrlParser": true, "useFindAndModify": false, "useCreateIndex": true}
readers:
    baudRate: 19200
    bitlen: 1
    parity: "mark"
    retryAttempts: 3
    retryDelay: 1000
    readerPort: "COM12"
    portCount: 1
    responseTimer: 2000
    hangTimer: 3000
apikey: "cf88928eb8234624bc45dee384fb3ed4"